<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnAddToCart</name>
   <tag></tag>
   <elementGuidId>255f070a-4fb3-4a1c-94cc-c8161ebcff1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@class='btn btn-success btn-lg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>ed52f84a-5a32-4511-9bb1-daf5e3533961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1695566761173</value>
      <webElementGuid>1459ab36-4c87-405f-8562-35193a6bf739</webElementGuid>
   </webElementProperties>
</WebElementEntity>
