<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>imgProducDetail</name>
   <tag></tag>
   <elementGuidId>57a0d008-749e-4585-bc0b-e2b9b91ba098</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='item active']//img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>218f6a0c-be58-4b60-8d31-a90e55ab3c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1695566787884</value>
      <webElementGuid>1f6d3241-bd8a-4021-9276-1048062e10ee</webElementGuid>
   </webElementProperties>
</WebElementEntity>
