<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>priceProductDetail</name>
   <tag></tag>
   <elementGuidId>500907f5-acf8-459e-955a-ee1ab73a197d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.price-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h3[@class='price-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>4e42e74f-43aa-4242-bdf8-0ed291823a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price-container</value>
      <webElementGuid>006a9d1d-5abb-4c46-81c9-87322b4a9a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$650 *includes tax</value>
      <webElementGuid>6ee733fc-3827-4705-a65e-42640697399f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbodyid&quot;)/h3[@class=&quot;price-container&quot;]</value>
      <webElementGuid>15fa9e4a-1b83-40b3-95cf-9d4b3f9b9db2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbodyid']/h3</value>
      <webElementGuid>5b90b6cd-84bf-47a1-903b-9ea93e4cb654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nexus 6'])[1]/following::h3[1]</value>
      <webElementGuid>c2a06b98-ef9d-4393-b4a8-188261336f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart'])[1]/following::h3[1]</value>
      <webElementGuid>2cefdb57-1e9c-4339-a8a4-0850dce200ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product description'])[1]/preceding::h3[1]</value>
      <webElementGuid>106da370-c43d-48af-aa3d-81a254f1c150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$650']/parent::*</value>
      <webElementGuid>0d033834-f3b3-4aa9-a935-da6975bca3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>a559e20f-d95c-4226-8c98-c588d07612a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = '$650 *includes tax' or . = '$650 *includes tax')]</value>
      <webElementGuid>3b371f9d-bb9f-453e-9f4b-3325c389c4a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
