<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>productDesc</name>
   <tag></tag>
   <elementGuidId>5f1e6aec-0d4e-4fb9-975c-deb8f09a776d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='more-information']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>1822e7e4-3a8d-4a8f-98ed-59e25770c266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1695566724557</value>
      <webElementGuid>d6d32ac6-b92b-46cb-8720-47131033e120</webElementGuid>
   </webElementProperties>
</WebElementEntity>
