<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titleProductDesc</name>
   <tag></tag>
   <elementGuidId>bd2e7a92-94b0-4069-9c25-2a08ad7d0364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='more-information']/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>3ba56242-e391-4643-9310-c74665576f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1695566310420</value>
      <webElementGuid>0999dcf4-ae3e-4aed-aff6-9f9f2ac09d19</webElementGuid>
   </webElementProperties>
</WebElementEntity>
