<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>totalPrice</name>
   <tag></tag>
   <elementGuidId>11a07798-8501-4d0d-bc04-30b56974d58d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#totalp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='totalp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>474cf19f-b676-48f6-b099-cc6db553c185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-title</value>
      <webElementGuid>d4ae9c0a-6c7a-4ac3-bc5b-d0c230cf48fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>totalp</value>
      <webElementGuid>d176a93f-67b8-4601-9a0a-85ca05c0a6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1440</value>
      <webElementGuid>aaf27b79-bb76-4748-9bf8-a9ada08ba8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;totalp&quot;)</value>
      <webElementGuid>fb2dca2f-3c69-4fb3-8711-63fdbc849dc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='totalp']</value>
      <webElementGuid>9ce51cb9-25c9-483a-9ce1-1c4ff9026eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div/div[2]/div/div/h3</value>
      <webElementGuid>e86a2fd2-874d-497c-a2ab-8b28525bcdb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::h3[1]</value>
      <webElementGuid>5f9987ee-12d4-415b-ab0f-568062e1d90b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nexus 6'])[1]/following::h3[1]</value>
      <webElementGuid>f741ea73-36b3-4af3-9400-72f96baed324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Place Order'])[1]/preceding::h3[1]</value>
      <webElementGuid>7bbb1d6e-14be-40b1-8586-c162cb096efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/preceding::h3[1]</value>
      <webElementGuid>377fd794-540b-4cb0-8f95-f20b729db39d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1440']/parent::*</value>
      <webElementGuid>86608562-f7f5-4df5-944b-227fdc7b907c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>d0207cb4-ab94-421d-b83c-ca4f554f2f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'totalp' and (text() = '1440' or . = '1440')]</value>
      <webElementGuid>3cbbe16a-e108-44d1-bddf-c6da9e72e191</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
